name = "api"
main = ".output/server/index.mjs"
compatibility_date = "2024-11-01"
assets = { directory = "./.output/public", binding = "ASSETS" }

rules = [{ type = "ESModule", globs = ["**/*.js", "**/*.mjs"] }]

[observability]
enabled = true
